### PR TITLE
Deleted extra files

### PR DESCRIPTION
**Pull request by Riddhi1992**
Deleted extra files and will commit updated files.

### CODE REVIEW

**Comment by Patibandha** [comment]
it doesn't have any file change

**Comment by Patibandha** [comment]
git reset --hard upstream/master

**Comment by Patibandha** [comment]
then commit

**Comment by Patibandha** [comment]
It doesn't have anything
also remember to create PR for each question's answer

**Comment by Riddhi1992** [comment]
I think I have deleted extra file and commit it that is why you are not able see any files here.
As you have told previously that O have to commit everything if I am adding/deleting file.

**Comment by Patibandha** [comment]
re base everything and then create 1 PR for each question's answer and test cases. No more, no less

**Pull request closed without merging**
